/*
 * This is a listener for the N1QL parser generated by analyzing the goyacc N1QL parser.
 */

import antlr4 from 'antlr4';
import n1qlLexer from './n1qlParser/n1qlLexer.js';
import n1qlParser from './n1qlParser/n1qlParser.js';
import n1qlListener from './n1qlParser/n1qlListener.js';
import * as fs from 'fs';

const { CommonTokenStream, InputStream } = antlr4;

class myN1qlListener extends n1qlListener {
  // Enter a parse tree produced by n1qlParser#input.
  enterInput(ctx) {
    console.log("enterInput");
  }

  // Exit a parse tree produced by n1qlParser#input.
  exitInput(ctx) {
    console.log("exitInput");
  }


  // Enter a parse tree produced by n1qlParser#opt_trailer.
  enterOpt_trailer(ctx) {
    console.log("enterOpt_trailer");
  }

  // Exit a parse tree produced by n1qlParser#opt_trailer.
  exitOpt_trailer(ctx) {
    console.log("exitOpt_trailer");
  }


  // Enter a parse tree produced by n1qlParser#stmt_body.
  enterStmt_body(ctx) {
    console.log("enterStmt_body");
  }

  // Exit a parse tree produced by n1qlParser#stmt_body.
  exitStmt_body(ctx) {
    console.log("exitStmt_body");
  }


  // Enter a parse tree produced by n1qlParser#stmt.
  enterStmt(ctx) {
    console.log("enterStmt");
  }

  // Exit a parse tree produced by n1qlParser#stmt.
  exitStmt(ctx) {
    console.log("exitStmt");
  }


  // Enter a parse tree produced by n1qlParser#advise.
  enterAdvise(ctx) {
    console.log("enterAdvise");
  }

  // Exit a parse tree produced by n1qlParser#advise.
  exitAdvise(ctx) {
    console.log("exitAdvise");
  }


  // Enter a parse tree produced by n1qlParser#opt_index.
  enterOpt_index(ctx) {
    console.log("enterOpt_index");
  }

  // Exit a parse tree produced by n1qlParser#opt_index.
  exitOpt_index(ctx) {
    console.log("exitOpt_index");
  }


  // Enter a parse tree produced by n1qlParser#explain.
  enterExplain(ctx) {
    console.log("enterExplain");
  }

  // Exit a parse tree produced by n1qlParser#explain.
  exitExplain(ctx) {
    console.log("exitExplain");
  }


  // Enter a parse tree produced by n1qlParser#prepare.
  enterPrepare(ctx) {
    console.log("enterPrepare");
  }

  // Exit a parse tree produced by n1qlParser#prepare.
  exitPrepare(ctx) {
    console.log("exitPrepare");
  }


  // Enter a parse tree produced by n1qlParser#opt_force.
  enterOpt_force(ctx) {
    console.log("enterOpt_force");
  }

  // Exit a parse tree produced by n1qlParser#opt_force.
  exitOpt_force(ctx) {
    console.log("exitOpt_force");
  }


  // Enter a parse tree produced by n1qlParser#opt_name.
  enterOpt_name(ctx) {
    console.log("enterOpt_name");
  }

  // Exit a parse tree produced by n1qlParser#opt_name.
  exitOpt_name(ctx) {
    console.log("exitOpt_name");
  }


  // Enter a parse tree produced by n1qlParser#from_or_as.
  enterFrom_or_as(ctx) {
    console.log("enterFrom_or_as");
  }

  // Exit a parse tree produced by n1qlParser#from_or_as.
  exitFrom_or_as(ctx) {
    console.log("exitFrom_or_as");
  }


  // Enter a parse tree produced by n1qlParser#execute.
  enterExecute(ctx) {
    console.log("enterExecute");
  }

  // Exit a parse tree produced by n1qlParser#execute.
  exitExecute(ctx) {
    console.log("exitExecute");
  }


  // Enter a parse tree produced by n1qlParser#execute_using.
  enterExecute_using(ctx) {
    console.log("enterExecute_using");
  }

  // Exit a parse tree produced by n1qlParser#execute_using.
  exitExecute_using(ctx) {
    console.log("exitExecute_using");
  }


  // Enter a parse tree produced by n1qlParser#infer.
  enterInfer(ctx) {
    console.log("enterInfer");
  }

  // Exit a parse tree produced by n1qlParser#infer.
  exitInfer(ctx) {
    console.log("exitInfer");
  }


  // Enter a parse tree produced by n1qlParser#opt_keyspace_collection.
  enterOpt_keyspace_collection(ctx) {
    console.log("enterOpt_keyspace_collection");
  }

  // Exit a parse tree produced by n1qlParser#opt_keyspace_collection.
  exitOpt_keyspace_collection(ctx) {
    console.log("exitOpt_keyspace_collection");
  }


  // Enter a parse tree produced by n1qlParser#opt_infer_using.
  enterOpt_infer_using(ctx) {
    console.log("enterOpt_infer_using");
  }

  // Exit a parse tree produced by n1qlParser#opt_infer_using.
  exitOpt_infer_using(ctx) {
    console.log("exitOpt_infer_using");
  }


  // Enter a parse tree produced by n1qlParser#opt_infer_ustat_with.
  enterOpt_infer_ustat_with(ctx) {
    console.log("enterOpt_infer_ustat_with");
  }

  // Exit a parse tree produced by n1qlParser#opt_infer_ustat_with.
  exitOpt_infer_ustat_with(ctx) {
    console.log("exitOpt_infer_ustat_with");
  }


  // Enter a parse tree produced by n1qlParser#infer_ustat_with.
  enterInfer_ustat_with(ctx) {
    console.log("enterInfer_ustat_with");
  }

  // Exit a parse tree produced by n1qlParser#infer_ustat_with.
  exitInfer_ustat_with(ctx) {
    console.log("exitInfer_ustat_with");
  }


  // Enter a parse tree produced by n1qlParser#select_stmt.
  enterSelect_stmt(ctx) {
    console.log("enterSelect_stmt");
  }

  // Exit a parse tree produced by n1qlParser#select_stmt.
  exitSelect_stmt(ctx) {
    console.log("exitSelect_stmt");
  }


  // Enter a parse tree produced by n1qlParser#dml_stmt.
  enterDml_stmt(ctx) {
    console.log("enterDml_stmt");
  }

  // Exit a parse tree produced by n1qlParser#dml_stmt.
  exitDml_stmt(ctx) {
    console.log("exitDml_stmt");
  }


  // Enter a parse tree produced by n1qlParser#ddl_stmt.
  enterDdl_stmt(ctx) {
    console.log("enterDdl_stmt");
  }

  // Exit a parse tree produced by n1qlParser#ddl_stmt.
  exitDdl_stmt(ctx) {
    console.log("exitDdl_stmt");
  }


  // Enter a parse tree produced by n1qlParser#role_stmt.
  enterRole_stmt(ctx) {
    console.log("enterRole_stmt");
  }

  // Exit a parse tree produced by n1qlParser#role_stmt.
  exitRole_stmt(ctx) {
    console.log("exitRole_stmt");
  }


  // Enter a parse tree produced by n1qlParser#index_stmt.
  enterIndex_stmt(ctx) {
    console.log("enterIndex_stmt");
  }

  // Exit a parse tree produced by n1qlParser#index_stmt.
  exitIndex_stmt(ctx) {
    console.log("exitIndex_stmt");
  }


  // Enter a parse tree produced by n1qlParser#scope_stmt.
  enterScope_stmt(ctx) {
    console.log("enterScope_stmt");
  }

  // Exit a parse tree produced by n1qlParser#scope_stmt.
  exitScope_stmt(ctx) {
    console.log("exitScope_stmt");
  }


  // Enter a parse tree produced by n1qlParser#collection_stmt.
  enterCollection_stmt(ctx) {
    console.log("enterCollection_stmt");
  }

  // Exit a parse tree produced by n1qlParser#collection_stmt.
  exitCollection_stmt(ctx) {
    console.log("exitCollection_stmt");
  }


  // Enter a parse tree produced by n1qlParser#function_stmt.
  enterFunction_stmt(ctx) {
    console.log("enterFunction_stmt");
  }

  // Exit a parse tree produced by n1qlParser#function_stmt.
  exitFunction_stmt(ctx) {
    console.log("exitFunction_stmt");
  }


  // Enter a parse tree produced by n1qlParser#transaction_stmt.
  enterTransaction_stmt(ctx) {
    console.log("enterTransaction_stmt");
  }

  // Exit a parse tree produced by n1qlParser#transaction_stmt.
  exitTransaction_stmt(ctx) {
    console.log("exitTransaction_stmt");
  }


  // Enter a parse tree produced by n1qlParser#fullselect.
  enterFullselect(ctx) {
    console.log("enterFullselect");
  }

  // Exit a parse tree produced by n1qlParser#fullselect.
  exitFullselect(ctx) {
    console.log("exitFullselect");
  }


  // Enter a parse tree produced by n1qlParser#select_terms.
  enterSelect_terms(ctx) {
    console.log("enterSelect_terms");
  }

  // Exit a parse tree produced by n1qlParser#select_terms.
  exitSelect_terms(ctx) {
    console.log("exitSelect_terms");
  }


  // Enter a parse tree produced by n1qlParser#select_term.
  enterSelect_term(ctx) {
    console.log("enterSelect_term");
  }

  // Exit a parse tree produced by n1qlParser#select_term.
  exitSelect_term(ctx) {
    console.log("exitSelect_term");
  }


  // Enter a parse tree produced by n1qlParser#subselect.
  enterSubselect(ctx) {
    console.log("enterSubselect");
  }

  // Exit a parse tree produced by n1qlParser#subselect.
  exitSubselect(ctx) {
    console.log("exitSubselect");
  }


  // Enter a parse tree produced by n1qlParser#from_select.
  enterFrom_select(ctx) {
    console.log("enterFrom_select");
  }

  // Exit a parse tree produced by n1qlParser#from_select.
  exitFrom_select(ctx) {
    console.log("exitFrom_select");
  }


  // Enter a parse tree produced by n1qlParser#select_from.
  enterSelect_from(ctx) {
    console.log("enterSelect_from");
  }

  // Exit a parse tree produced by n1qlParser#select_from.
  exitSelect_from(ctx) {
    console.log("exitSelect_from");
  }


  // Enter a parse tree produced by n1qlParser#select_clause.
  enterSelect_clause(ctx) {
    console.log("enterSelect_clause");
  }

  // Exit a parse tree produced by n1qlParser#select_clause.
  exitSelect_clause(ctx) {
    console.log("exitSelect_clause");
  }


  // Enter a parse tree produced by n1qlParser#projection.
  enterProjection(ctx) {
    console.log("enterProjection");
  }

  // Exit a parse tree produced by n1qlParser#projection.
  exitProjection(ctx) {
    console.log("exitProjection");
  }


  // Enter a parse tree produced by n1qlParser#opt_quantifier.
  enterOpt_quantifier(ctx) {
    console.log("enterOpt_quantifier");
  }

  // Exit a parse tree produced by n1qlParser#opt_quantifier.
  exitOpt_quantifier(ctx) {
    console.log("exitOpt_quantifier");
  }


  // Enter a parse tree produced by n1qlParser#raw.
  enterRaw(ctx) {
    console.log("enterRaw");
  }

  // Exit a parse tree produced by n1qlParser#raw.
  exitRaw(ctx) {  console.log("exitRaw");
  }


  // Enter a parse tree produced by n1qlParser#projects.
  enterProjects(ctx) {
    console.log("enterProjects");
  }

  // Exit a parse tree produced by n1qlParser#projects.
  exitProjects(ctx) {
    console.log("exitProjects");
  }


  // Enter a parse tree produced by n1qlParser#project.
  enterProject(ctx) {
    console.log("enterProject");
  }

  // Exit a parse tree produced by n1qlParser#project.
  exitProject(ctx) {
    console.log("exitProject");
  }


  // Enter a parse tree produced by n1qlParser#opt_as_alias.
  enterOpt_as_alias(ctx) {
    console.log("enterOpt_as_alias");
  }

  // Exit a parse tree produced by n1qlParser#opt_as_alias.
  exitOpt_as_alias(ctx) {
    console.log("exitOpt_as_alias");
  }


  // Enter a parse tree produced by n1qlParser#as_alias.
  enterAs_alias(ctx) {
    console.log("enterAs_alias");
  }

  // Exit a parse tree produced by n1qlParser#as_alias.
  exitAs_alias(ctx) {
    console.log("exitAs_alias");
  }


  // Enter a parse tree produced by n1qlParser#alias.
  enterAlias(ctx) {
    console.log("enterAlias");
  }

  // Exit a parse tree produced by n1qlParser#alias.
  exitAlias(ctx) {
    console.log("exitAlias");
  }


  // Enter a parse tree produced by n1qlParser#opt_from.
  enterOpt_from(ctx) {
    console.log("enterOpt_from");
  }

  // Exit a parse tree produced by n1qlParser#opt_from.
  exitOpt_from(ctx) {
    console.log("exitOpt_from");
  }


  // Enter a parse tree produced by n1qlParser#from.
  enterFrom(ctx) {
    console.log("enterFrom");
  }

  // Exit a parse tree produced by n1qlParser#from.
  exitFrom(ctx) {
    console.log("exitFrom");
  }


  // Enter a parse tree produced by n1qlParser#from_term.
  enterFrom_term(ctx) {
    console.log("enterFrom_term");
  }

  // Exit a parse tree produced by n1qlParser#from_term.
  exitFrom_term(ctx) {
    console.log("exitFrom_term");
  }


  // Enter a parse tree produced by n1qlParser#simple_from_term.
  enterSimple_from_term(ctx) {
    console.log("enterSimple_from_term");
  }

  // Exit a parse tree produced by n1qlParser#simple_from_term.
  exitSimple_from_term(ctx) {
    console.log("exitSimple_from_term");
  }


  // Enter a parse tree produced by n1qlParser#unnest.
  enterUnnest(ctx) {
    console.log("enterUnnest");
  }

  // Exit a parse tree produced by n1qlParser#unnest.
  exitUnnest(ctx) {
    console.log("exitUnnest");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_term.
  enterKeyspace_term(ctx) {
    console.log("enterKeyspace_term");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_term.
  exitKeyspace_term(ctx) {
    console.log("exitKeyspace_term");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_path.
  enterKeyspace_path(ctx) {
    console.log("enterKeyspace_path");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_path.
  exitKeyspace_path(ctx) {
    console.log("exitKeyspace_path");
  }


  // Enter a parse tree produced by n1qlParser#namespace_term.
  enterNamespace_term(ctx) {
    console.log("enterNamespace_term");
  }

  // Exit a parse tree produced by n1qlParser#namespace_term.
  exitNamespace_term(ctx) {
    console.log("exitNamespace_term");
  }


  // Enter a parse tree produced by n1qlParser#namespace_name.
  enterNamespace_name(ctx) {
    console.log("enterNamespace_name");
  }

  // Exit a parse tree produced by n1qlParser#namespace_name.
  exitNamespace_name(ctx) {
    console.log("exitNamespace_name");
  }


  // Enter a parse tree produced by n1qlParser#bucket_name.
  enterBucket_name(ctx) {
    console.log("enterBucket_name");
  }

  // Exit a parse tree produced by n1qlParser#bucket_name.
  exitBucket_name(ctx) {
    console.log("exitBucket_name");
  }


  // Enter a parse tree produced by n1qlParser#scope_name.
  enterScope_name(ctx) {
    console.log("enterScope_name");
  }

  // Exit a parse tree produced by n1qlParser#scope_name.
  exitScope_name(ctx) {
    console.log("exitScope_name");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_name.
  enterKeyspace_name(ctx) {
    console.log("enterKeyspace_name");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_name.
  exitKeyspace_name(ctx) {
    console.log("exitKeyspace_name");
  }


  // Enter a parse tree produced by n1qlParser#opt_use.
  enterOpt_use(ctx) {
    console.log("enterOpt_use");
  }

  // Exit a parse tree produced by n1qlParser#opt_use.
  exitOpt_use(ctx) {
    console.log("exitOpt_use");
  }


  // Enter a parse tree produced by n1qlParser#use_options.
  enterUse_options(ctx) {
    console.log("enterUse_options");
  }

  // Exit a parse tree produced by n1qlParser#use_options.
  exitUse_options(ctx) {
    console.log("exitUse_options");
  }


  // Enter a parse tree produced by n1qlParser#use_keys.
  enterUse_keys(ctx) {
    console.log("enterUse_keys");
  }

  // Exit a parse tree produced by n1qlParser#use_keys.
  exitUse_keys(ctx) {
    console.log("exitUse_keys");
  }


  // Enter a parse tree produced by n1qlParser#use_index.
  enterUse_index(ctx) {
    console.log("enterUse_index");
  }

  // Exit a parse tree produced by n1qlParser#use_index.
  exitUse_index(ctx) {
    console.log("exitUse_index");
  }


  // Enter a parse tree produced by n1qlParser#join_hint.
  enterJoin_hint(ctx) {
    console.log("enterJoin_hint");
  }

  // Exit a parse tree produced by n1qlParser#join_hint.
  exitJoin_hint(ctx) {
    console.log("exitJoin_hint");
  }


  // Enter a parse tree produced by n1qlParser#opt_primary.
  enterOpt_primary(ctx) {
    console.log("enterOpt_primary");
  }

  // Exit a parse tree produced by n1qlParser#opt_primary.
  exitOpt_primary(ctx) {
    console.log("exitOpt_primary");
  }


  // Enter a parse tree produced by n1qlParser#index_refs.
  enterIndex_refs(ctx) {
    console.log("enterIndex_refs");
  }

  // Exit a parse tree produced by n1qlParser#index_refs.
  exitIndex_refs(ctx) {
    console.log("exitIndex_refs");
  }


  // Enter a parse tree produced by n1qlParser#index_ref.
  enterIndex_ref(ctx) {
    console.log("enterIndex_ref");
  }

  // Exit a parse tree produced by n1qlParser#index_ref.
  exitIndex_ref(ctx) {
    console.log("exitIndex_ref");
  }


  // Enter a parse tree produced by n1qlParser#use_hash_option.
  enterUse_hash_option(ctx) {
    console.log("enterUse_hash_option");
  }

  // Exit a parse tree produced by n1qlParser#use_hash_option.
  exitUse_hash_option(ctx) {
    console.log("exitUse_hash_option");
  }


  // Enter a parse tree produced by n1qlParser#opt_use_del_upd.
  enterOpt_use_del_upd(ctx) {
    console.log("enterOpt_use_del_upd");
  }

  // Exit a parse tree produced by n1qlParser#opt_use_del_upd.
  exitOpt_use_del_upd(ctx) {
    console.log("exitOpt_use_del_upd");
  }


  // Enter a parse tree produced by n1qlParser#opt_join_type.
  enterOpt_join_type(ctx) {
    console.log("enterOpt_join_type");
  }

  // Exit a parse tree produced by n1qlParser#opt_join_type.
  exitOpt_join_type(ctx) {
    console.log("exitOpt_join_type");
  }


  // Enter a parse tree produced by n1qlParser#opt_outer.
  enterOpt_outer(ctx) {
    console.log("enterOpt_outer");
  }

  // Exit a parse tree produced by n1qlParser#opt_outer.
  exitOpt_outer(ctx) {
    console.log("exitOpt_outer");
  }


  // Enter a parse tree produced by n1qlParser#on_keys.
  enterOn_keys(ctx) {
    console.log("enterOn_keys");
  }

  // Exit a parse tree produced by n1qlParser#on_keys.
  exitOn_keys(ctx) {
    console.log("exitOn_keys");
  }


  // Enter a parse tree produced by n1qlParser#on_key.
  enterOn_key(ctx) {
    console.log("enterOn_key");
  }

  // Exit a parse tree produced by n1qlParser#on_key.
  exitOn_key(ctx) {
    console.log("exitOn_key");
  }


  // Enter a parse tree produced by n1qlParser#opt_let.
  enterOpt_let(ctx) {
    console.log("enterOpt_let");
  }

  // Exit a parse tree produced by n1qlParser#opt_let.
  exitOpt_let(ctx) {
    console.log("exitOpt_let");
  }


  // Enter a parse tree produced by n1qlParser#let_.
  enterLet_(ctx) {
    console.log("enterLet_");
  }

  // Exit a parse tree produced by n1qlParser#let_.
  exitLet_(ctx) {
    console.log("exitLet_");
  }


  // Enter a parse tree produced by n1qlParser#bindings.
  enterBindings(ctx) {
    console.log("enterBindings");
  }

  // Exit a parse tree produced by n1qlParser#bindings.
  exitBindings(ctx) {
    console.log("exitBindings");
  }


  // Enter a parse tree produced by n1qlParser#binding.
  enterBinding(ctx) {
    console.log("enterBinding");
  }

  // Exit a parse tree produced by n1qlParser#binding.
  exitBinding(ctx) {
    console.log("exitBinding");
  }


  // Enter a parse tree produced by n1qlParser#opt_with.
  enterOpt_with(ctx) {
    console.log("enterOpt_with");
  }

  // Exit a parse tree produced by n1qlParser#opt_with.
  exitOpt_with(ctx) {
    console.log("exitOpt_with");
  }


  // Enter a parse tree produced by n1qlParser#with_list.
  enterWith_list(ctx) {
    console.log("enterWith_list");
  }

  // Exit a parse tree produced by n1qlParser#with_list.
  exitWith_list(ctx) {
    console.log("exitWith_list");
  }


  // Enter a parse tree produced by n1qlParser#with_term.
  enterWith_term(ctx) {
    console.log("enterWith_term");
  }

  // Exit a parse tree produced by n1qlParser#with_term.
  exitWith_term(ctx) {
    console.log("exitWith_term");
  }


  // Enter a parse tree produced by n1qlParser#opt_where.
  enterOpt_where(ctx) {
    console.log("enterOpt_where");
  }

  // Exit a parse tree produced by n1qlParser#opt_where.
  exitOpt_where(ctx) {
    console.log("exitOpt_where");
  }


  // Enter a parse tree produced by n1qlParser#where.
  enterWhere(ctx) {
    console.log("enterWhere");
  }

  // Exit a parse tree produced by n1qlParser#where.
  exitWhere(ctx) {
    console.log("exitWhere");
  }


  // Enter a parse tree produced by n1qlParser#opt_group.
  enterOpt_group(ctx) {
    console.log("enterOpt_group");
  }

  // Exit a parse tree produced by n1qlParser#opt_group.
  exitOpt_group(ctx) {
    console.log("exitOpt_group");
  }


  // Enter a parse tree produced by n1qlParser#group.
  enterGroup(ctx) {
    console.log("enterGroup");
  }

  // Exit a parse tree produced by n1qlParser#group.
  exitGroup(ctx) {
    console.log("exitGroup");
  }


  // Enter a parse tree produced by n1qlParser#group_terms.
  enterGroup_terms(ctx) {
    console.log("enterGroup_terms");
  }

  // Exit a parse tree produced by n1qlParser#group_terms.
  exitGroup_terms(ctx) {
    console.log("exitGroup_terms");
  }


  // Enter a parse tree produced by n1qlParser#group_term.
  enterGroup_term(ctx) {
    console.log("enterGroup_term");
  }

  // Exit a parse tree produced by n1qlParser#group_term.
  exitGroup_term(ctx) {
    console.log("exitGroup_term");
  }


  // Enter a parse tree produced by n1qlParser#opt_letting.
  enterOpt_letting(ctx) {
    console.log("enterOpt_letting");
  }

  // Exit a parse tree produced by n1qlParser#opt_letting.
  exitOpt_letting(ctx) {
    console.log("exitOpt_letting");
  }


  // Enter a parse tree produced by n1qlParser#letting.
  enterLetting(ctx) {
    console.log("enterLetting");
  }

  // Exit a parse tree produced by n1qlParser#letting.
  exitLetting(ctx) {
    console.log("exitLetting");
  }


  // Enter a parse tree produced by n1qlParser#opt_having.
  enterOpt_having(ctx) {
    console.log("enterOpt_having");
  }

  // Exit a parse tree produced by n1qlParser#opt_having.
  exitOpt_having(ctx) {
    console.log("exitOpt_having");
  }


  // Enter a parse tree produced by n1qlParser#having.
  enterHaving(ctx) {
    console.log("enterHaving");
  }

  // Exit a parse tree produced by n1qlParser#having.
  exitHaving(ctx) {
    console.log("exitHaving");
  }


  // Enter a parse tree produced by n1qlParser#opt_order_by.
  enterOpt_order_by(ctx) {
    console.log("enterOpt_order_by");
  }

  // Exit a parse tree produced by n1qlParser#opt_order_by.
  exitOpt_order_by(ctx) {
    console.log("exitOpt_order_by");
  }


  // Enter a parse tree produced by n1qlParser#order_by.
  enterOrder_by(ctx) {
    console.log("enterOrder_by");
  }

  // Exit a parse tree produced by n1qlParser#order_by.
  exitOrder_by(ctx) {
    console.log("exitOrder_by");
  }


  // Enter a parse tree produced by n1qlParser#sort_terms.
  enterSort_terms(ctx) {
    console.log("enterSort_terms");
  }

  // Exit a parse tree produced by n1qlParser#sort_terms.
  exitSort_terms(ctx) {
    console.log("exitSort_terms");
  }


  // Enter a parse tree produced by n1qlParser#sort_term.
  enterSort_term(ctx) {
    console.log("enterSort_term");
  }

  // Exit a parse tree produced by n1qlParser#sort_term.
  exitSort_term(ctx) {
    console.log("exitSort_term");
  }


  // Enter a parse tree produced by n1qlParser#opt_dir.
  enterOpt_dir(ctx) {
    console.log("enterOpt_dir");
  }

  // Exit a parse tree produced by n1qlParser#opt_dir.
  exitOpt_dir(ctx) {
    console.log("exitOpt_dir");
  }


  // Enter a parse tree produced by n1qlParser#dir.
  enterDir(ctx) {
    console.log("enterDir");
  }

  // Exit a parse tree produced by n1qlParser#dir.
  exitDir(ctx) {  console.log("exitDir");
  }


  // Enter a parse tree produced by n1qlParser#opt_order_nulls.
  enterOpt_order_nulls(ctx) {
    console.log("enterOpt_order_nulls");
  }

  // Exit a parse tree produced by n1qlParser#opt_order_nulls.
  exitOpt_order_nulls(ctx) {
    console.log("exitOpt_order_nulls");
  }


  // Enter a parse tree produced by n1qlParser#first_last.
  enterFirst_last(ctx) {
    console.log("enterFirst_last");
  }

  // Exit a parse tree produced by n1qlParser#first_last.
  exitFirst_last(ctx) {
    console.log("exitFirst_last");
  }


  // Enter a parse tree produced by n1qlParser#nulls.
  enterNulls(ctx) {
    console.log("enterNulls");
  }

  // Exit a parse tree produced by n1qlParser#nulls.
  exitNulls(ctx) {
    console.log("exitNulls");
  }


  // Enter a parse tree produced by n1qlParser#opt_limit.
  enterOpt_limit(ctx) {
    console.log("enterOpt_limit");
  }

  // Exit a parse tree produced by n1qlParser#opt_limit.
  exitOpt_limit(ctx) {
    console.log("exitOpt_limit");
  }


  // Enter a parse tree produced by n1qlParser#limit.
  enterLimit(ctx) {
    console.log("enterLimit");
  }

  // Exit a parse tree produced by n1qlParser#limit.
  exitLimit(ctx) {
    console.log("exitLimit");
  }


  // Enter a parse tree produced by n1qlParser#opt_offset.
  enterOpt_offset(ctx) {
    console.log("enterOpt_offset");
  }

  // Exit a parse tree produced by n1qlParser#opt_offset.
  exitOpt_offset(ctx) {
    console.log("exitOpt_offset");
  }


  // Enter a parse tree produced by n1qlParser#offset.
  enterOffset(ctx) {
    console.log("enterOffset");
  }

  // Exit a parse tree produced by n1qlParser#offset.
  exitOffset(ctx) {
    console.log("exitOffset");
  }


  // Enter a parse tree produced by n1qlParser#insert.
  enterInsert(ctx) {
    console.log("enterInsert");
  }

  // Exit a parse tree produced by n1qlParser#insert.
  exitInsert(ctx) {
    console.log("exitInsert");
  }


  // Enter a parse tree produced by n1qlParser#simple_keyspace_ref.
  enterSimple_keyspace_ref(ctx) {
    console.log("enterSimple_keyspace_ref");
  }

  // Exit a parse tree produced by n1qlParser#simple_keyspace_ref.
  exitSimple_keyspace_ref(ctx) {
    console.log("exitSimple_keyspace_ref");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_ref.
  enterKeyspace_ref(ctx) {
    console.log("enterKeyspace_ref");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_ref.
  exitKeyspace_ref(ctx) {
    console.log("exitKeyspace_ref");
  }


  // Enter a parse tree produced by n1qlParser#opt_values_header.
  enterOpt_values_header(ctx) {
    console.log("enterOpt_values_header");
  }

  // Exit a parse tree produced by n1qlParser#opt_values_header.
  exitOpt_values_header(ctx) {
    console.log("exitOpt_values_header");
  }


  // Enter a parse tree produced by n1qlParser#key.
  enterKey(ctx) {
    console.log("enterKey");
  }

  // Exit a parse tree produced by n1qlParser#key.
  exitKey(ctx) {  console.log("exitKey");
  }


  // Enter a parse tree produced by n1qlParser#values_list.
  enterValues_list(ctx) {
    console.log("enterValues_list");
  }

  // Exit a parse tree produced by n1qlParser#values_list.
  exitValues_list(ctx) {
    console.log("exitValues_list");
  }


  // Enter a parse tree produced by n1qlParser#values.
  enterValues(ctx) {
    console.log("enterValues");
  }

  // Exit a parse tree produced by n1qlParser#values.
  exitValues(ctx) {
    console.log("exitValues");
  }


  // Enter a parse tree produced by n1qlParser#next_values.
  enterNext_values(ctx) {
    console.log("enterNext_values");
  }

  // Exit a parse tree produced by n1qlParser#next_values.
  exitNext_values(ctx) {
    console.log("exitNext_values");
  }


  // Enter a parse tree produced by n1qlParser#key_val_expr.
  enterKey_val_expr(ctx) {
    console.log("enterKey_val_expr");
  }

  // Exit a parse tree produced by n1qlParser#key_val_expr.
  exitKey_val_expr(ctx) {
    console.log("exitKey_val_expr");
  }


  // Enter a parse tree produced by n1qlParser#key_val_options_expr.
  enterKey_val_options_expr(ctx) {
    console.log("enterKey_val_options_expr");
  }

  // Exit a parse tree produced by n1qlParser#key_val_options_expr.
  exitKey_val_options_expr(ctx) {
    console.log("exitKey_val_options_expr");
  }


  // Enter a parse tree produced by n1qlParser#opt_returning.
  enterOpt_returning(ctx) {
    console.log("enterOpt_returning");
  }

  // Exit a parse tree produced by n1qlParser#opt_returning.
  exitOpt_returning(ctx) {
    console.log("exitOpt_returning");
  }


  // Enter a parse tree produced by n1qlParser#returning.
  enterReturning(ctx) {
    console.log("enterReturning");
  }

  // Exit a parse tree produced by n1qlParser#returning.
  exitReturning(ctx) {
    console.log("exitReturning");
  }


  // Enter a parse tree produced by n1qlParser#returns_.
  enterReturns_(ctx) {
    console.log("enterReturns_");
  }

  // Exit a parse tree produced by n1qlParser#returns_.
  exitReturns_(ctx) {
    console.log("exitReturns_");
  }


  // Enter a parse tree produced by n1qlParser#key_expr_header.
  enterKey_expr_header(ctx) {
    console.log("enterKey_expr_header");
  }

  // Exit a parse tree produced by n1qlParser#key_expr_header.
  exitKey_expr_header(ctx) {
    console.log("exitKey_expr_header");
  }


  // Enter a parse tree produced by n1qlParser#value_expr_header.
  enterValue_expr_header(ctx) {
    console.log("enterValue_expr_header");
  }

  // Exit a parse tree produced by n1qlParser#value_expr_header.
  exitValue_expr_header(ctx) {
    console.log("exitValue_expr_header");
  }


  // Enter a parse tree produced by n1qlParser#options_expr_header.
  enterOptions_expr_header(ctx) {
    console.log("enterOptions_expr_header");
  }

  // Exit a parse tree produced by n1qlParser#options_expr_header.
  exitOptions_expr_header(ctx) {
    console.log("exitOptions_expr_header");
  }


  // Enter a parse tree produced by n1qlParser#key_val_options_expr_header.
  enterKey_val_options_expr_header(ctx) {
    console.log("enterKey_val_options_expr_header");
  }

  // Exit a parse tree produced by n1qlParser#key_val_options_expr_header.
  exitKey_val_options_expr_header(ctx) {
    console.log("exitKey_val_options_expr_header");
  }


  // Enter a parse tree produced by n1qlParser#upsert.
  enterUpsert(ctx) {
    console.log("enterUpsert");
  }

  // Exit a parse tree produced by n1qlParser#upsert.
  exitUpsert(ctx) {
    console.log("exitUpsert");
  }


  // Enter a parse tree produced by n1qlParser#delete_.
  enterDelete_(ctx) {
    console.log("enterDelete_");
  }

  // Exit a parse tree produced by n1qlParser#delete_.
  exitDelete_(ctx) {
    console.log("exitDelete_");
  }


  // Enter a parse tree produced by n1qlParser#update.
  enterUpdate(ctx) {
    console.log("enterUpdate");
  }

  // Exit a parse tree produced by n1qlParser#update.
  exitUpdate(ctx) {
    console.log("exitUpdate");
  }


  // Enter a parse tree produced by n1qlParser#set.
  enterSet(ctx) {
    console.log("enterSet");
  }

  // Exit a parse tree produced by n1qlParser#set.
  exitSet(ctx) {  console.log("exitSet");
  }


  // Enter a parse tree produced by n1qlParser#set_terms.
  enterSet_terms(ctx) {
    console.log("enterSet_terms");
  }

  // Exit a parse tree produced by n1qlParser#set_terms.
  exitSet_terms(ctx) {
    console.log("exitSet_terms");
  }


  // Enter a parse tree produced by n1qlParser#set_term.
  enterSet_term(ctx) {
    console.log("enterSet_term");
  }

  // Exit a parse tree produced by n1qlParser#set_term.
  exitSet_term(ctx) {
    console.log("exitSet_term");
  }


  // Enter a parse tree produced by n1qlParser#function_meta_expr.
  enterFunction_meta_expr(ctx) {
    console.log("enterFunction_meta_expr");
  }

  // Exit a parse tree produced by n1qlParser#function_meta_expr.
  exitFunction_meta_expr(ctx) {
    console.log("exitFunction_meta_expr");
  }


  // Enter a parse tree produced by n1qlParser#opt_update_for.
  enterOpt_update_for(ctx) {
    console.log("enterOpt_update_for");
  }

  // Exit a parse tree produced by n1qlParser#opt_update_for.
  exitOpt_update_for(ctx) {
    console.log("exitOpt_update_for");
  }


  // Enter a parse tree produced by n1qlParser#update_for.
  enterUpdate_for(ctx) {
    console.log("enterUpdate_for");
  }

  // Exit a parse tree produced by n1qlParser#update_for.
  exitUpdate_for(ctx) {
    console.log("exitUpdate_for");
  }


  // Enter a parse tree produced by n1qlParser#update_dimensions.
  enterUpdate_dimensions(ctx) {
    console.log("enterUpdate_dimensions");
  }

  // Exit a parse tree produced by n1qlParser#update_dimensions.
  exitUpdate_dimensions(ctx) {
    console.log("exitUpdate_dimensions");
  }


  // Enter a parse tree produced by n1qlParser#update_dimension.
  enterUpdate_dimension(ctx) {
    console.log("enterUpdate_dimension");
  }

  // Exit a parse tree produced by n1qlParser#update_dimension.
  exitUpdate_dimension(ctx) {
    console.log("exitUpdate_dimension");
  }


  // Enter a parse tree produced by n1qlParser#update_binding.
  enterUpdate_binding(ctx) {
    console.log("enterUpdate_binding");
  }

  // Exit a parse tree produced by n1qlParser#update_binding.
  exitUpdate_binding(ctx) {
    console.log("exitUpdate_binding");
  }


  // Enter a parse tree produced by n1qlParser#variable.
  enterVariable(ctx) {
    console.log("enterVariable");
  }

  // Exit a parse tree produced by n1qlParser#variable.
  exitVariable(ctx) {
    console.log("exitVariable");
  }


  // Enter a parse tree produced by n1qlParser#opt_when.
  enterOpt_when(ctx) {
    console.log("enterOpt_when");
  }

  // Exit a parse tree produced by n1qlParser#opt_when.
  exitOpt_when(ctx) {
    console.log("exitOpt_when");
  }


  // Enter a parse tree produced by n1qlParser#unset.
  enterUnset(ctx) {
    console.log("enterUnset");
  }

  // Exit a parse tree produced by n1qlParser#unset.
  exitUnset(ctx) {
    console.log("exitUnset");
  }


  // Enter a parse tree produced by n1qlParser#unset_terms.
  enterUnset_terms(ctx) {
    console.log("enterUnset_terms");
  }

  // Exit a parse tree produced by n1qlParser#unset_terms.
  exitUnset_terms(ctx) {
    console.log("exitUnset_terms");
  }


  // Enter a parse tree produced by n1qlParser#unset_term.
  enterUnset_term(ctx) {
    console.log("enterUnset_term");
  }

  // Exit a parse tree produced by n1qlParser#unset_term.
  exitUnset_term(ctx) {
    console.log("exitUnset_term");
  }


  // Enter a parse tree produced by n1qlParser#merge.
  enterMerge(ctx) {
    console.log("enterMerge");
  }

  // Exit a parse tree produced by n1qlParser#merge.
  exitMerge(ctx) {
    console.log("exitMerge");
  }


  // Enter a parse tree produced by n1qlParser#opt_use_merge.
  enterOpt_use_merge(ctx) {
    console.log("enterOpt_use_merge");
  }

  // Exit a parse tree produced by n1qlParser#opt_use_merge.
  exitOpt_use_merge(ctx) {
    console.log("exitOpt_use_merge");
  }


  // Enter a parse tree produced by n1qlParser#opt_key.
  enterOpt_key(ctx) {
    console.log("enterOpt_key");
  }

  // Exit a parse tree produced by n1qlParser#opt_key.
  exitOpt_key(ctx) {
    console.log("exitOpt_key");
  }


  // Enter a parse tree produced by n1qlParser#merge_actions.
  enterMerge_actions(ctx) {
    console.log("enterMerge_actions");
  }

  // Exit a parse tree produced by n1qlParser#merge_actions.
  exitMerge_actions(ctx) {
    console.log("exitMerge_actions");
  }


  // Enter a parse tree produced by n1qlParser#opt_merge_delete_insert.
  enterOpt_merge_delete_insert(ctx) {
    console.log("enterOpt_merge_delete_insert");
  }

  // Exit a parse tree produced by n1qlParser#opt_merge_delete_insert.
  exitOpt_merge_delete_insert(ctx) {
    console.log("exitOpt_merge_delete_insert");
  }


  // Enter a parse tree produced by n1qlParser#opt_merge_insert.
  enterOpt_merge_insert(ctx) {
    console.log("enterOpt_merge_insert");
  }

  // Exit a parse tree produced by n1qlParser#opt_merge_insert.
  exitOpt_merge_insert(ctx) {
    console.log("exitOpt_merge_insert");
  }


  // Enter a parse tree produced by n1qlParser#merge_update.
  enterMerge_update(ctx) {
    console.log("enterMerge_update");
  }

  // Exit a parse tree produced by n1qlParser#merge_update.
  exitMerge_update(ctx) {
    console.log("exitMerge_update");
  }


  // Enter a parse tree produced by n1qlParser#merge_delete.
  enterMerge_delete(ctx) {
    console.log("enterMerge_delete");
  }

  // Exit a parse tree produced by n1qlParser#merge_delete.
  exitMerge_delete(ctx) {
    console.log("exitMerge_delete");
  }


  // Enter a parse tree produced by n1qlParser#merge_insert.
  enterMerge_insert(ctx) {
    console.log("enterMerge_insert");
  }

  // Exit a parse tree produced by n1qlParser#merge_insert.
  exitMerge_insert(ctx) {
    console.log("exitMerge_insert");
  }


  // Enter a parse tree produced by n1qlParser#grant_role.
  enterGrant_role(ctx) {
    console.log("enterGrant_role");
  }

  // Exit a parse tree produced by n1qlParser#grant_role.
  exitGrant_role(ctx) {
    console.log("exitGrant_role");
  }


  // Enter a parse tree produced by n1qlParser#role_list.
  enterRole_list(ctx) {
    console.log("enterRole_list");
  }

  // Exit a parse tree produced by n1qlParser#role_list.
  exitRole_list(ctx) {
    console.log("exitRole_list");
  }


  // Enter a parse tree produced by n1qlParser#role_name.
  enterRole_name(ctx) {
    console.log("enterRole_name");
  }

  // Exit a parse tree produced by n1qlParser#role_name.
  exitRole_name(ctx) {
    console.log("exitRole_name");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_scope_list.
  enterKeyspace_scope_list(ctx) {
    console.log("enterKeyspace_scope_list");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_scope_list.
  exitKeyspace_scope_list(ctx) {
    console.log("exitKeyspace_scope_list");
  }


  // Enter a parse tree produced by n1qlParser#keyspace_scope.
  enterKeyspace_scope(ctx) {
    console.log("enterKeyspace_scope");
  }

  // Exit a parse tree produced by n1qlParser#keyspace_scope.
  exitKeyspace_scope(ctx) {
    console.log("exitKeyspace_scope");
  }


  // Enter a parse tree produced by n1qlParser#user_list.
  enterUser_list(ctx) {
    console.log("enterUser_list");
  }

  // Exit a parse tree produced by n1qlParser#user_list.
  exitUser_list(ctx) {
    console.log("exitUser_list");
  }


  // Enter a parse tree produced by n1qlParser#user.
  enterUser(ctx) {
    console.log("enterUser");
  }

  // Exit a parse tree produced by n1qlParser#user.
  exitUser(ctx) {
    console.log("exitUser");
  }


  // Enter a parse tree produced by n1qlParser#revoke_role.
  enterRevoke_role(ctx) {
    console.log("enterRevoke_role");
  }

  // Exit a parse tree produced by n1qlParser#revoke_role.
  exitRevoke_role(ctx) {
    console.log("exitRevoke_role");
  }


  // Enter a parse tree produced by n1qlParser#create_scope.
  enterCreate_scope(ctx) {
    console.log("enterCreate_scope");
  }

  // Exit a parse tree produced by n1qlParser#create_scope.
  exitCreate_scope(ctx) {
    console.log("exitCreate_scope");
  }


  // Enter a parse tree produced by n1qlParser#drop_scope.
  enterDrop_scope(ctx) {
    console.log("enterDrop_scope");
  }

  // Exit a parse tree produced by n1qlParser#drop_scope.
  exitDrop_scope(ctx) {
    console.log("exitDrop_scope");
  }


  // Enter a parse tree produced by n1qlParser#create_collection.
  enterCreate_collection(ctx) {
    console.log("enterCreate_collection");
  }

  // Exit a parse tree produced by n1qlParser#create_collection.
  exitCreate_collection(ctx) {
    console.log("exitCreate_collection");
  }


  // Enter a parse tree produced by n1qlParser#drop_collection.
  enterDrop_collection(ctx) {
    console.log("enterDrop_collection");
  }

  // Exit a parse tree produced by n1qlParser#drop_collection.
  exitDrop_collection(ctx) {
    console.log("exitDrop_collection");
  }


  // Enter a parse tree produced by n1qlParser#flush_collection.
  enterFlush_collection(ctx) {
    console.log("enterFlush_collection");
  }

  // Exit a parse tree produced by n1qlParser#flush_collection.
  exitFlush_collection(ctx) {
    console.log("exitFlush_collection");
  }


  // Enter a parse tree produced by n1qlParser#flush_or_truncate.
  enterFlush_or_truncate(ctx) {
    console.log("enterFlush_or_truncate");
  }

  // Exit a parse tree produced by n1qlParser#flush_or_truncate.
  exitFlush_or_truncate(ctx) {
    console.log("exitFlush_or_truncate");
  }


  // Enter a parse tree produced by n1qlParser#create_index.
  enterCreate_index(ctx) {
    console.log("enterCreate_index");
  }

  // Exit a parse tree produced by n1qlParser#create_index.
  exitCreate_index(ctx) {
    console.log("exitCreate_index");
  }


  // Enter a parse tree produced by n1qlParser#opt_primary_name.
  enterOpt_primary_name(ctx) {
    console.log("enterOpt_primary_name");
  }

  // Exit a parse tree produced by n1qlParser#opt_primary_name.
  exitOpt_primary_name(ctx) {
    console.log("exitOpt_primary_name");
  }


  // Enter a parse tree produced by n1qlParser#index_name.
  enterIndex_name(ctx) {
    console.log("enterIndex_name");
  }

  // Exit a parse tree produced by n1qlParser#index_name.
  exitIndex_name(ctx) {
    console.log("exitIndex_name");
  }


  // Enter a parse tree produced by n1qlParser#opt_index_name.
  enterOpt_index_name(ctx) {
    console.log("enterOpt_index_name");
  }

  // Exit a parse tree produced by n1qlParser#opt_index_name.
  exitOpt_index_name(ctx) {
    console.log("exitOpt_index_name");
  }


  // Enter a parse tree produced by n1qlParser#named_keyspace_ref.
  enterNamed_keyspace_ref(ctx) {
    console.log("enterNamed_keyspace_ref");
  }

  // Exit a parse tree produced by n1qlParser#named_keyspace_ref.
  exitNamed_keyspace_ref(ctx) {
    console.log("exitNamed_keyspace_ref");
  }


  // Enter a parse tree produced by n1qlParser#simple_named_keyspace_ref.
  enterSimple_named_keyspace_ref(ctx) {
    console.log("enterSimple_named_keyspace_ref");
  }

  // Exit a parse tree produced by n1qlParser#simple_named_keyspace_ref.
  exitSimple_named_keyspace_ref(ctx) {
    console.log("exitSimple_named_keyspace_ref");
  }


  // Enter a parse tree produced by n1qlParser#named_scope_ref.
  enterNamed_scope_ref(ctx) {
    console.log("enterNamed_scope_ref");
  }

  // Exit a parse tree produced by n1qlParser#named_scope_ref.
  exitNamed_scope_ref(ctx) {
    console.log("exitNamed_scope_ref");
  }


  // Enter a parse tree produced by n1qlParser#index_partition.
  enterIndex_partition(ctx) {
    console.log("enterIndex_partition");
  }

  // Exit a parse tree produced by n1qlParser#index_partition.
  exitIndex_partition(ctx) {
    console.log("exitIndex_partition");
  }


  // Enter a parse tree produced by n1qlParser#opt_index_using.
  enterOpt_index_using(ctx) {
    console.log("enterOpt_index_using");
  }

  // Exit a parse tree produced by n1qlParser#opt_index_using.
  exitOpt_index_using(ctx) {
    console.log("exitOpt_index_using");
  }


  // Enter a parse tree produced by n1qlParser#index_using.
  enterIndex_using(ctx) {
    console.log("enterIndex_using");
  }

  // Exit a parse tree produced by n1qlParser#index_using.
  exitIndex_using(ctx) {
    console.log("exitIndex_using");
  }


  // Enter a parse tree produced by n1qlParser#opt_index_with.
  enterOpt_index_with(ctx) {
    console.log("enterOpt_index_with");
  }

  // Exit a parse tree produced by n1qlParser#opt_index_with.
  exitOpt_index_with(ctx) {
    console.log("exitOpt_index_with");
  }


  // Enter a parse tree produced by n1qlParser#index_with.
  enterIndex_with(ctx) {
    console.log("enterIndex_with");
  }

  // Exit a parse tree produced by n1qlParser#index_with.
  exitIndex_with(ctx) {
    console.log("exitIndex_with");
  }


  // Enter a parse tree produced by n1qlParser#index_terms.
  enterIndex_terms(ctx) {
    console.log("enterIndex_terms");
  }

  // Exit a parse tree produced by n1qlParser#index_terms.
  exitIndex_terms(ctx) {
    console.log("exitIndex_terms");
  }


  // Enter a parse tree produced by n1qlParser#index_term.
  enterIndex_term(ctx) {
    console.log("enterIndex_term");
  }

  // Exit a parse tree produced by n1qlParser#index_term.
  exitIndex_term(ctx) {
    console.log("exitIndex_term");
  }


  // Enter a parse tree produced by n1qlParser#index_term_expr.
  enterIndex_term_expr(ctx) {
    console.log("enterIndex_term_expr");
  }

  // Exit a parse tree produced by n1qlParser#index_term_expr.
  exitIndex_term_expr(ctx) {
    console.log("exitIndex_term_expr");
  }


  // Enter a parse tree produced by n1qlParser#index_expr.
  enterIndex_expr(ctx) {
    console.log("enterIndex_expr");
  }

  // Exit a parse tree produced by n1qlParser#index_expr.
  exitIndex_expr(ctx) {
    console.log("exitIndex_expr");
  }


  // Enter a parse tree produced by n1qlParser#all.
  enterAll(ctx) {
    console.log("enterAll");
  }

  // Exit a parse tree produced by n1qlParser#all.
  exitAll(ctx) {  console.log("exitAll");
  }


  // Enter a parse tree produced by n1qlParser#index_where.
  enterIndex_where(ctx) {
    console.log("enterIndex_where");
  }

  // Exit a parse tree produced by n1qlParser#index_where.
  exitIndex_where(ctx) {
    console.log("exitIndex_where");
  }


  // Enter a parse tree produced by n1qlParser#opt_ikattr.
  enterOpt_ikattr(ctx) {
    console.log("enterOpt_ikattr");
  }

  // Exit a parse tree produced by n1qlParser#opt_ikattr.
  exitOpt_ikattr(ctx) {
    console.log("exitOpt_ikattr");
  }


  // Enter a parse tree produced by n1qlParser#ikattr.
  enterIkattr(ctx) {
    console.log("enterIkattr");
  }

  // Exit a parse tree produced by n1qlParser#ikattr.
  exitIkattr(ctx) {
    console.log("exitIkattr");
  }


  // Enter a parse tree produced by n1qlParser#drop_index.
  enterDrop_index(ctx) {
    console.log("enterDrop_index");
  }

  // Exit a parse tree produced by n1qlParser#drop_index.
  exitDrop_index(ctx) {
    console.log("exitDrop_index");
  }


  // Enter a parse tree produced by n1qlParser#alter_index.
  enterAlter_index(ctx) {
    console.log("enterAlter_index");
  }

  // Exit a parse tree produced by n1qlParser#alter_index.
  exitAlter_index(ctx) {
    console.log("exitAlter_index");
  }


  // Enter a parse tree produced by n1qlParser#build_index.
  enterBuild_index(ctx) {
    console.log("enterBuild_index");
  }

  // Exit a parse tree produced by n1qlParser#build_index.
  exitBuild_index(ctx) {
    console.log("exitBuild_index");
  }


  // Enter a parse tree produced by n1qlParser#create_function.
  enterCreate_function(ctx) {
    console.log("enterCreate_function");
  }

  // Exit a parse tree produced by n1qlParser#create_function.
  exitCreate_function(ctx) {
    console.log("exitCreate_function");
  }


  // Enter a parse tree produced by n1qlParser#opt_replace.
  enterOpt_replace(ctx) {
    console.log("enterOpt_replace");
  }

  // Exit a parse tree produced by n1qlParser#opt_replace.
  exitOpt_replace(ctx) {
    console.log("exitOpt_replace");
  }


  // Enter a parse tree produced by n1qlParser#func_name.
  enterFunc_name(ctx) {
    console.log("enterFunc_name");
  }

  // Exit a parse tree produced by n1qlParser#func_name.
  exitFunc_name(ctx) {
    console.log("exitFunc_name");
  }


  // Enter a parse tree produced by n1qlParser#short_func_name.
  enterShort_func_name(ctx) {
    console.log("enterShort_func_name");
  }

  // Exit a parse tree produced by n1qlParser#short_func_name.
  exitShort_func_name(ctx) {
    console.log("exitShort_func_name");
  }


  // Enter a parse tree produced by n1qlParser#long_func_name.
  enterLong_func_name(ctx) {
    console.log("enterLong_func_name");
  }

  // Exit a parse tree produced by n1qlParser#long_func_name.
  exitLong_func_name(ctx) {
    console.log("exitLong_func_name");
  }


  // Enter a parse tree produced by n1qlParser#parm_list.
  enterParm_list(ctx) {
    console.log("enterParm_list");
  }

  // Exit a parse tree produced by n1qlParser#parm_list.
  exitParm_list(ctx) {
    console.log("exitParm_list");
  }


  // Enter a parse tree produced by n1qlParser#parameter_terms.
  enterParameter_terms(ctx) {
    console.log("enterParameter_terms");
  }

  // Exit a parse tree produced by n1qlParser#parameter_terms.
  exitParameter_terms(ctx) {
    console.log("exitParameter_terms");
  }


  // Enter a parse tree produced by n1qlParser#func_body.
  enterFunc_body(ctx) {
    console.log("enterFunc_body");
  }

  // Exit a parse tree produced by n1qlParser#func_body.
  exitFunc_body(ctx) {
    console.log("exitFunc_body");
  }


  // Enter a parse tree produced by n1qlParser#drop_function.
  enterDrop_function(ctx) {
    console.log("enterDrop_function");
  }

  // Exit a parse tree produced by n1qlParser#drop_function.
  exitDrop_function(ctx) {
    console.log("exitDrop_function");
  }


  // Enter a parse tree produced by n1qlParser#execute_function.
  enterExecute_function(ctx) {
    console.log("enterExecute_function");
  }

  // Exit a parse tree produced by n1qlParser#execute_function.
  exitExecute_function(ctx) {
    console.log("exitExecute_function");
  }


  // Enter a parse tree produced by n1qlParser#update_statistics.
  enterUpdate_statistics(ctx) {
    console.log("enterUpdate_statistics");
  }

  // Exit a parse tree produced by n1qlParser#update_statistics.
  exitUpdate_statistics(ctx) {
    console.log("exitUpdate_statistics");
  }


  // Enter a parse tree produced by n1qlParser#opt_for.
  enterOpt_for(ctx) {
    console.log("enterOpt_for");
  }

  // Exit a parse tree produced by n1qlParser#opt_for.
  exitOpt_for(ctx) {
    console.log("exitOpt_for");
  }


  // Enter a parse tree produced by n1qlParser#update_stat_terms.
  enterUpdate_stat_terms(ctx) {
    console.log("enterUpdate_stat_terms");
  }

  // Exit a parse tree produced by n1qlParser#update_stat_terms.
  exitUpdate_stat_terms(ctx) {
    console.log("exitUpdate_stat_terms");
  }


  // Enter a parse tree produced by n1qlParser#update_stat_term.
  enterUpdate_stat_term(ctx) {
    console.log("enterUpdate_stat_term");
  }

  // Exit a parse tree produced by n1qlParser#update_stat_term.
  exitUpdate_stat_term(ctx) {
    console.log("exitUpdate_stat_term");
  }


  // Enter a parse tree produced by n1qlParser#path.
  enterPath(ctx) {
    console.log("enterPath");
  }

  // Exit a parse tree produced by n1qlParser#path.
  exitPath(ctx) {
    console.log("exitPath");
  }


  // Enter a parse tree produced by n1qlParser#expr.
  enterExpr(ctx) {
    console.log("enterExpr");
  }

  // Exit a parse tree produced by n1qlParser#expr.
  exitExpr(ctx) {
    console.log("exitExpr");
  }


  // Enter a parse tree produced by n1qlParser#valued.
  enterValued(ctx) {
    console.log("enterValued");
  }

  // Exit a parse tree produced by n1qlParser#valued.
  exitValued(ctx) {
    console.log("exitValued");
  }


  // Enter a parse tree produced by n1qlParser#c_expr.
  enterC_expr(ctx) {
    console.log("enterC_expr");
  }

  // Exit a parse tree produced by n1qlParser#c_expr.
  exitC_expr(ctx) {
    console.log("exitC_expr");
  }


  // Enter a parse tree produced by n1qlParser#b_expr.
  enterB_expr(ctx) {
    console.log("enterB_expr");
  }

  // Exit a parse tree produced by n1qlParser#b_expr.
  exitB_expr(ctx) {
    console.log("exitB_expr");
  }


  // Enter a parse tree produced by n1qlParser#literal.
  enterLiteral(ctx) {
    console.log("enterLiteral");
  }

  // Exit a parse tree produced by n1qlParser#literal.
  exitLiteral(ctx) {
    console.log("exitLiteral");
  }


  // Enter a parse tree produced by n1qlParser#construction_expr.
  enterConstruction_expr(ctx) {
    console.log("enterConstruction_expr");
  }

  // Exit a parse tree produced by n1qlParser#construction_expr.
  exitConstruction_expr(ctx) {
    console.log("exitConstruction_expr");
  }


  // Enter a parse tree produced by n1qlParser#object.
  enterObject(ctx) {
    console.log("enterObject");
  }

  // Exit a parse tree produced by n1qlParser#object.
  exitObject(ctx) {
    console.log("exitObject");
  }


  // Enter a parse tree produced by n1qlParser#opt_members.
  enterOpt_members(ctx) {
    console.log("enterOpt_members");
  }

  // Exit a parse tree produced by n1qlParser#opt_members.
  exitOpt_members(ctx) {
    console.log("exitOpt_members");
  }


  // Enter a parse tree produced by n1qlParser#members.
  enterMembers(ctx) {
    console.log("enterMembers");
  }

  // Exit a parse tree produced by n1qlParser#members.
  exitMembers(ctx) {
    console.log("exitMembers");
  }


  // Enter a parse tree produced by n1qlParser#member.
  enterMember(ctx) {
    console.log("enterMember");
  }

  // Exit a parse tree produced by n1qlParser#member.
  exitMember(ctx) {
    console.log("exitMember");
  }


  // Enter a parse tree produced by n1qlParser#array.
  enterArray(ctx) {
    console.log("enterArray");
  }

  // Exit a parse tree produced by n1qlParser#array.
  exitArray(ctx) {
    console.log("exitArray");
  }


  // Enter a parse tree produced by n1qlParser#opt_exprs.
  enterOpt_exprs(ctx) {
    console.log("enterOpt_exprs");
  }

  // Exit a parse tree produced by n1qlParser#opt_exprs.
  exitOpt_exprs(ctx) {
    console.log("exitOpt_exprs");
  }


  // Enter a parse tree produced by n1qlParser#exprs.
  enterExprs(ctx) {
    console.log("enterExprs");
  }

  // Exit a parse tree produced by n1qlParser#exprs.
  exitExprs(ctx) {
    console.log("exitExprs");
  }


  // Enter a parse tree produced by n1qlParser#param_expr.
  enterParam_expr(ctx) {
    console.log("enterParam_expr");
  }

  // Exit a parse tree produced by n1qlParser#param_expr.
  exitParam_expr(ctx) {
    console.log("exitParam_expr");
  }


  // Enter a parse tree produced by n1qlParser#case_expr.
  enterCase_expr(ctx) {
    console.log("enterCase_expr");
  }

  // Exit a parse tree produced by n1qlParser#case_expr.
  exitCase_expr(ctx) {
    console.log("exitCase_expr");
  }


  // Enter a parse tree produced by n1qlParser#simple_or_searched_case.
  enterSimple_or_searched_case(ctx) {
    console.log("enterSimple_or_searched_case");
  }

  // Exit a parse tree produced by n1qlParser#simple_or_searched_case.
  exitSimple_or_searched_case(ctx) {
    console.log("exitSimple_or_searched_case");
  }


  // Enter a parse tree produced by n1qlParser#simple_case.
  enterSimple_case(ctx) {
    console.log("enterSimple_case");
  }

  // Exit a parse tree produced by n1qlParser#simple_case.
  exitSimple_case(ctx) {
    console.log("exitSimple_case");
  }


  // Enter a parse tree produced by n1qlParser#when_thens.
  enterWhen_thens(ctx) {
    console.log("enterWhen_thens");
  }

  // Exit a parse tree produced by n1qlParser#when_thens.
  exitWhen_thens(ctx) {
    console.log("exitWhen_thens");
  }


  // Enter a parse tree produced by n1qlParser#searched_case.
  enterSearched_case(ctx) {
    console.log("enterSearched_case");
  }

  // Exit a parse tree produced by n1qlParser#searched_case.
  exitSearched_case(ctx) {
    console.log("exitSearched_case");
  }


  // Enter a parse tree produced by n1qlParser#opt_else.
  enterOpt_else(ctx) {
    console.log("enterOpt_else");
  }

  // Exit a parse tree produced by n1qlParser#opt_else.
  exitOpt_else(ctx) {
    console.log("exitOpt_else");
  }


  // Enter a parse tree produced by n1qlParser#function_expr.
  enterFunction_expr(ctx) {
    console.log("enterFunction_expr");
  }

  // Exit a parse tree produced by n1qlParser#function_expr.
  exitFunction_expr(ctx) {
    console.log("exitFunction_expr");
  }


  // Enter a parse tree produced by n1qlParser#function_name.
  enterFunction_name(ctx) {
    console.log("enterFunction_name");
  }

  // Exit a parse tree produced by n1qlParser#function_name.
  exitFunction_name(ctx) {
    console.log("exitFunction_name");
  }


  // Enter a parse tree produced by n1qlParser#collection_expr.
  enterCollection_expr(ctx) {
    console.log("enterCollection_expr");
  }

  // Exit a parse tree produced by n1qlParser#collection_expr.
  exitCollection_expr(ctx) {
    console.log("exitCollection_expr");
  }


  // Enter a parse tree produced by n1qlParser#collection_cond.
  enterCollection_cond(ctx) {
    console.log("enterCollection_cond");
  }

  // Exit a parse tree produced by n1qlParser#collection_cond.
  exitCollection_cond(ctx) {
    console.log("exitCollection_cond");
  }


  // Enter a parse tree produced by n1qlParser#coll_bindings.
  enterColl_bindings(ctx) {
    console.log("enterColl_bindings");
  }

  // Exit a parse tree produced by n1qlParser#coll_bindings.
  exitColl_bindings(ctx) {
    console.log("exitColl_bindings");
  }


  // Enter a parse tree produced by n1qlParser#coll_binding.
  enterColl_binding(ctx) {
    console.log("enterColl_binding");
  }

  // Exit a parse tree produced by n1qlParser#coll_binding.
  exitColl_binding(ctx) {
    console.log("exitColl_binding");
  }


  // Enter a parse tree produced by n1qlParser#satisfies.
  enterSatisfies(ctx) {
    console.log("enterSatisfies");
  }

  // Exit a parse tree produced by n1qlParser#satisfies.
  exitSatisfies(ctx) {
    console.log("exitSatisfies");
  }


  // Enter a parse tree produced by n1qlParser#collection_xform.
  enterCollection_xform(ctx) {
    console.log("enterCollection_xform");
  }

  // Exit a parse tree produced by n1qlParser#collection_xform.
  exitCollection_xform(ctx) {
    console.log("exitCollection_xform");
  }


  // Enter a parse tree produced by n1qlParser#paren_expr.
  enterParen_expr(ctx) {
    console.log("enterParen_expr");
  }

  // Exit a parse tree produced by n1qlParser#paren_expr.
  exitParen_expr(ctx) {
    console.log("exitParen_expr");
  }


  // Enter a parse tree produced by n1qlParser#subquery_expr.
  enterSubquery_expr(ctx) {
    console.log("enterSubquery_expr");
  }

  // Exit a parse tree produced by n1qlParser#subquery_expr.
  exitSubquery_expr(ctx) {
    console.log("exitSubquery_expr");
  }


  // Enter a parse tree produced by n1qlParser#expr_input.
  enterExpr_input(ctx) {
    console.log("enterExpr_input");
  }

  // Exit a parse tree produced by n1qlParser#expr_input.
  exitExpr_input(ctx) {
    console.log("exitExpr_input");
  }


  // Enter a parse tree produced by n1qlParser#all_expr.
  enterAll_expr(ctx) {
    console.log("enterAll_expr");
  }

  // Exit a parse tree produced by n1qlParser#all_expr.
  exitAll_expr(ctx) {
    console.log("exitAll_expr");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_clause.
  enterOpt_window_clause(ctx) {
    console.log("enterOpt_window_clause");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_clause.
  exitOpt_window_clause(ctx) {
    console.log("exitOpt_window_clause");
  }


  // Enter a parse tree produced by n1qlParser#window_list.
  enterWindow_list(ctx) {
    console.log("enterWindow_list");
  }

  // Exit a parse tree produced by n1qlParser#window_list.
  exitWindow_list(ctx) {
    console.log("exitWindow_list");
  }


  // Enter a parse tree produced by n1qlParser#window_term.
  enterWindow_term(ctx) {
    console.log("enterWindow_term");
  }

  // Exit a parse tree produced by n1qlParser#window_term.
  exitWindow_term(ctx) {
    console.log("exitWindow_term");
  }


  // Enter a parse tree produced by n1qlParser#window_specification.
  enterWindow_specification(ctx) {
    console.log("enterWindow_specification");
  }

  // Exit a parse tree produced by n1qlParser#window_specification.
  exitWindow_specification(ctx) {
    console.log("exitWindow_specification");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_name.
  enterOpt_window_name(ctx) {
    console.log("enterOpt_window_name");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_name.
  exitOpt_window_name(ctx) {
    console.log("exitOpt_window_name");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_partition.
  enterOpt_window_partition(ctx) {
    console.log("enterOpt_window_partition");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_partition.
  exitOpt_window_partition(ctx) {
    console.log("exitOpt_window_partition");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_frame.
  enterOpt_window_frame(ctx) {
    console.log("enterOpt_window_frame");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_frame.
  exitOpt_window_frame(ctx) {
    console.log("exitOpt_window_frame");
  }


  // Enter a parse tree produced by n1qlParser#window_frame_modifier.
  enterWindow_frame_modifier(ctx) {
    console.log("enterWindow_frame_modifier");
  }

  // Exit a parse tree produced by n1qlParser#window_frame_modifier.
  exitWindow_frame_modifier(ctx) {
    console.log("exitWindow_frame_modifier");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_frame_exclusion.
  enterOpt_window_frame_exclusion(ctx) {
    console.log("enterOpt_window_frame_exclusion");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_frame_exclusion.
  exitOpt_window_frame_exclusion(ctx) {
    console.log("exitOpt_window_frame_exclusion");
  }


  // Enter a parse tree produced by n1qlParser#window_frame_extents.
  enterWindow_frame_extents(ctx) {
    console.log("enterWindow_frame_extents");
  }

  // Exit a parse tree produced by n1qlParser#window_frame_extents.
  exitWindow_frame_extents(ctx) {
    console.log("exitWindow_frame_extents");
  }


  // Enter a parse tree produced by n1qlParser#window_frame_extent.
  enterWindow_frame_extent(ctx) {
    console.log("enterWindow_frame_extent");
  }

  // Exit a parse tree produced by n1qlParser#window_frame_extent.
  exitWindow_frame_extent(ctx) {
    console.log("exitWindow_frame_extent");
  }


  // Enter a parse tree produced by n1qlParser#window_frame_valexpr_modifier.
  enterWindow_frame_valexpr_modifier(ctx) {
    console.log("enterWindow_frame_valexpr_modifier");
  }

  // Exit a parse tree produced by n1qlParser#window_frame_valexpr_modifier.
  exitWindow_frame_valexpr_modifier(ctx) {
    console.log("exitWindow_frame_valexpr_modifier");
  }


  // Enter a parse tree produced by n1qlParser#opt_nulls_treatment.
  enterOpt_nulls_treatment(ctx) {
    console.log("enterOpt_nulls_treatment");
  }

  // Exit a parse tree produced by n1qlParser#opt_nulls_treatment.
  exitOpt_nulls_treatment(ctx) {
    console.log("exitOpt_nulls_treatment");
  }


  // Enter a parse tree produced by n1qlParser#nulls_treatment.
  enterNulls_treatment(ctx) {
    console.log("enterNulls_treatment");
  }

  // Exit a parse tree produced by n1qlParser#nulls_treatment.
  exitNulls_treatment(ctx) {
    console.log("exitNulls_treatment");
  }


  // Enter a parse tree produced by n1qlParser#opt_from_first_last.
  enterOpt_from_first_last(ctx) {
    console.log("enterOpt_from_first_last");
  }

  // Exit a parse tree produced by n1qlParser#opt_from_first_last.
  exitOpt_from_first_last(ctx) {
    console.log("exitOpt_from_first_last");
  }


  // Enter a parse tree produced by n1qlParser#agg_quantifier.
  enterAgg_quantifier(ctx) {
    console.log("enterAgg_quantifier");
  }

  // Exit a parse tree produced by n1qlParser#agg_quantifier.
  exitAgg_quantifier(ctx) {
    console.log("exitAgg_quantifier");
  }


  // Enter a parse tree produced by n1qlParser#opt_filter.
  enterOpt_filter(ctx) {
    console.log("enterOpt_filter");
  }

  // Exit a parse tree produced by n1qlParser#opt_filter.
  exitOpt_filter(ctx) {
    console.log("exitOpt_filter");
  }


  // Enter a parse tree produced by n1qlParser#opt_window_function.
  enterOpt_window_function(ctx) {
    console.log("enterOpt_window_function");
  }

  // Exit a parse tree produced by n1qlParser#opt_window_function.
  exitOpt_window_function(ctx) {
    console.log("exitOpt_window_function");
  }


  // Enter a parse tree produced by n1qlParser#window_function_details.
  enterWindow_function_details(ctx) {
    console.log("enterWindow_function_details");
  }

  // Exit a parse tree produced by n1qlParser#window_function_details.
  exitWindow_function_details(ctx) {
    console.log("exitWindow_function_details");
  }


  // Enter a parse tree produced by n1qlParser#start_transaction.
  enterStart_transaction(ctx) {
    console.log("enterStart_transaction");
  }

  // Exit a parse tree produced by n1qlParser#start_transaction.
  exitStart_transaction(ctx) {
    console.log("exitStart_transaction");
  }


  // Enter a parse tree produced by n1qlParser#commit_transaction.
  enterCommit_transaction(ctx) {
    console.log("enterCommit_transaction");
  }

  // Exit a parse tree produced by n1qlParser#commit_transaction.
  exitCommit_transaction(ctx) {
    console.log("exitCommit_transaction");
  }


  // Enter a parse tree produced by n1qlParser#rollback_transaction.
  enterRollback_transaction(ctx) {
    console.log("enterRollback_transaction");
  }

  // Exit a parse tree produced by n1qlParser#rollback_transaction.
  exitRollback_transaction(ctx) {
    console.log("exitRollback_transaction");
  }


  // Enter a parse tree produced by n1qlParser#start_or_begin.
  enterStart_or_begin(ctx) {
    console.log("enterStart_or_begin");
  }

  // Exit a parse tree produced by n1qlParser#start_or_begin.
  exitStart_or_begin(ctx) {
    console.log("exitStart_or_begin");
  }


  // Enter a parse tree produced by n1qlParser#opt_transaction.
  enterOpt_transaction(ctx) {
    console.log("enterOpt_transaction");
  }

  // Exit a parse tree produced by n1qlParser#opt_transaction.
  exitOpt_transaction(ctx) {
    console.log("exitOpt_transaction");
  }


  // Enter a parse tree produced by n1qlParser#transaction.
  enterTransaction(ctx) {
    console.log("enterTransaction");
  }

  // Exit a parse tree produced by n1qlParser#transaction.
  exitTransaction(ctx) {
    console.log("exitTransaction");
  }


  // Enter a parse tree produced by n1qlParser#opt_savepoint.
  enterOpt_savepoint(ctx) {
    console.log("enterOpt_savepoint");
  }

  // Exit a parse tree produced by n1qlParser#opt_savepoint.
  exitOpt_savepoint(ctx) {
    console.log("exitOpt_savepoint");
  }


  // Enter a parse tree produced by n1qlParser#savepoint_name.
  enterSavepoint_name(ctx) {
    console.log("enterSavepoint_name");
  }

  // Exit a parse tree produced by n1qlParser#savepoint_name.
  exitSavepoint_name(ctx) {
    console.log("exitSavepoint_name");
  }


  // Enter a parse tree produced by n1qlParser#opt_isolation_level.
  enterOpt_isolation_level(ctx) {
    console.log("enterOpt_isolation_level");
  }

  // Exit a parse tree produced by n1qlParser#opt_isolation_level.
  exitOpt_isolation_level(ctx) {
    console.log("exitOpt_isolation_level");
  }


  // Enter a parse tree produced by n1qlParser#isolation_level.
  enterIsolation_level(ctx) {
    console.log("enterIsolation_level");
  }

  // Exit a parse tree produced by n1qlParser#isolation_level.
  exitIsolation_level(ctx) {
    console.log("exitIsolation_level");
  }


  // Enter a parse tree produced by n1qlParser#isolation_val.
  enterIsolation_val(ctx) {
    console.log("enterIsolation_val");
  }

  // Exit a parse tree produced by n1qlParser#isolation_val.
  exitIsolation_val(ctx) {
    console.log("exitIsolation_val");
  }


  // Enter a parse tree produced by n1qlParser#set_transaction_isolation.
  enterSet_transaction_isolation(ctx) {
    console.log("enterSet_transaction_isolation");
  }

  // Exit a parse tree produced by n1qlParser#set_transaction_isolation.
  exitSet_transaction_isolation(ctx) {
    console.log("exitSet_transaction_isolation");
  }


  // Enter a parse tree produced by n1qlParser#savepoint.
  enterSavepoint(ctx) {
    console.log("enterSavepoint");
  }

  // Exit a parse tree produced by n1qlParser#savepoint.
  exitSavepoint(ctx) {
    console.log("exitSavepoint");
  }


}


function parseFile(fileName) {
  var n1ql = fs.readFileSync('../../../goproj/src/github.com/couchbase/query/parser/n1ql/n1ql.y').toString();
  parseString(n1ql);
}

function parse(n1ql) {
  var chars = new antlr4.InputStream(n1ql);
  var lexer = new n1qlLexer(chars);
  var tokens = new CommonTokenStream(lexer);
  var parser = new n1qlParser(tokens);

  var tree = parser.input();
  var listener = new myN1qlListener();

  antlr4.tree.ParseTreeWalker.DEFAULT.walk(listener, tree);
}

parse('select `beer-sample`.foo.bar from `beer-sample`');

var N1qlParser = {
  parse: parse,
  parseFile: parseFile,
};

export default N1qlParser;